version: "3.1"
services:
  islasgeci:
    build:
      context: .
      dockerfile: Dockerfile
    image: islasgeci/position_traps_to_geojson:latest
    command: bash
    volumes:
      - $PWD:/workdir